/**
 * Regenerates the cross-implementation format-2 fixture.
 *
 *   node --experimental-strip-types harness/make-v2-fixture.ts
 *
 * WHY THIS EXISTS. `core/` (TypeScript) and `ios/Sources/KeyholeCore` (Swift) are
 * independent implementations of one envelope format. Nothing in either build system
 * checks that they agree — interchange is guaranteed by shared format plus vector
 * tests, and this file is one of those vectors. It is committed so the Swift suite can
 * open a vault that TypeScript actually wrote, rather than one Swift wrote and then
 * congratulated itself on reading back.
 *
 * The Secret Key and Recovery Code are written alongside the envelope. They are not
 * secret: this vault contains one fabricated entry and exists only to be opened by a
 * test. Regenerate it whenever the envelope format, the AAD templates, the derivation
 * or the Secret Key encoding change — and if a regeneration is ever needed to make an
 * *existing* build pass, that is a compatibility break, not a stale fixture.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createEntry, createVault, saveVault } from '../src/index.ts';

const PASSWORD = 'interop-fixture-master-password';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '../../ios/Tests/KeyholeCoreTests/Fixtures/ts-v2-vault.json');

const created = await createVault(PASSWORD, { formatVersion: 2 });
const { data } = createEntry(created.session.data, {
  title: 'Interop',
  username: 'vector@example.com',
  password: 'written-by-typescript',
  urls: ['https://example.com/login'],
  notes: 'Fabricated. Exists to prove the Swift port reads what TypeScript writes.',
});
created.session.data = data;
const file = await saveVault(created.session, created.file);

await mkdir(dirname(outPath), { recursive: true });
await writeFile(
  outPath,
  `${JSON.stringify(
    {
      note: 'Generated by core/harness/make-v2-fixture.ts. Credentials below are not secret.',
      masterPassword: PASSWORD,
      secretKey: created.kit!.secretKey,
      recoveryCode: created.kit!.recoveryCode,
      entryPassword: 'written-by-typescript',
      vault: file,
    },
    null,
    2,
  )}\n`,
  'utf8',
);

console.log(`Wrote ${outPath}`);
console.log(`  secretKey:    ${created.kit!.secretKey}`);
console.log(`  recoveryCode: ${created.kit!.recoveryCode}`);
